---
name: codecov
on:
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - run: mvn install -Pjacoco
      - uses: codecov/codecov-action@v4
        with:
          file: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
